/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface StorageInterface extends Interface {
  getFunction(
    nameOrSignature: "getCount" | "records" | "storeResult"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Stored"): EventFragment;

  encodeFunctionData(functionFragment: "getCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "records",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "storeResult",
    values: [string, string]
  ): string;

  decodeFunctionResult(functionFragment: "getCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "records", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "storeResult",
    data: BytesLike
  ): Result;
}

export namespace StoredEvent {
  export type InputTuple = [
    user: AddressLike,
    encryptedText: string,
    decryptedText: string
  ];
  export type OutputTuple = [
    user: string,
    encryptedText: string,
    decryptedText: string
  ];
  export interface OutputObject {
    user: string;
    encryptedText: string;
    decryptedText: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Storage extends BaseContract {
  connect(runner?: ContractRunner | null): Storage;
  waitForDeployment(): Promise<this>;

  interface: StorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getCount: TypedContractMethod<[], [bigint], "view">;

  records: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        encryptedText: string;
        decryptedText: string;
        user: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  storeResult: TypedContractMethod<
    [_enc: string, _dec: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "records"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        encryptedText: string;
        decryptedText: string;
        user: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "storeResult"
  ): TypedContractMethod<[_enc: string, _dec: string], [void], "nonpayable">;

  getEvent(
    key: "Stored"
  ): TypedContractEvent<
    StoredEvent.InputTuple,
    StoredEvent.OutputTuple,
    StoredEvent.OutputObject
  >;

  filters: {
    "Stored(address,string,string)": TypedContractEvent<
      StoredEvent.InputTuple,
      StoredEvent.OutputTuple,
      StoredEvent.OutputObject
    >;
    Stored: TypedContractEvent<
      StoredEvent.InputTuple,
      StoredEvent.OutputTuple,
      StoredEvent.OutputObject
    >;
  };
}
